### ISSUE TITLE
ActivityNet

### ISSUE THREAD

**Issue by lpdone** [Lily1994/BTH#1]
Very good job！
Are you convenient to provide the features of the Activitynet dataset for reproduction and follow-up?

**Comment by Shuyan98** [comment]
Hi, I've uploaded the features to Tsinghua cloud pan https://cloud.tsinghua.edu.cn/d/5406c5fede254b2dadf6/. For each video, we equally sample 30 frames and process each of them with Resnet50. You can also download raw data at http://activity-net.org/ and extract features on your own.

**Comment by lpdone** [comment]
Thank you very much! !

**Comment by rovgtjktm66** [comment]
Hello, in the testing phase of the YFCC dataset, is it to use 1000 videos as the query and （101256-1000） videos as the database? Can labels be provided?  
Looking forward to your reply~
Thank you！
