### ISSUE TITLE
YFCC

### ISSUE THREAD

**Issue by lpdone** [Lily1994/BTH#2]
Hello, in the testing phase of the YFCC dataset, is it to use 1000 videos as the query and （101256-1000） videos as the database? Can labels be provided?
Looking forward to your reply~
Thank you！

**Comment by lpdone** [comment]
另外，您在activity数据集上怎么生成Latent features的呢，方便提供一下嘛？具体的比特数，epoch，batchsize是多少？仅用mask loss您得到了多少map@5呀？

**Comment by Shuyan98** [comment]
On YFCC: 1000 queries, all the test videos as retrieval database. query features&query labels& all test labels can be found here: https://cloud.tsinghua.edu.cn/d/056678341d2b46949cfd/
On Activitynet, map@5 of 64bits with only mask loss: 0.215.
The generation steps of latent features on ActivityNet are the same with that on FCVID. epoch: 250~300, batch size:256, bits:128.

**Comment by rovgtjktm66** [comment]
太感谢啦！！真好

**Comment by lpdone** [comment]
还想请教一下，yfcc_test_labels_1.mat为什么是81列，而query1000_labels.mat是80列？

**Comment by rovgtjktm66** [comment]
另外：生成latent features的模型，大概在 ActivityNet 数据集上 能达到多少MAP@5呢？

**Comment by lpdone** [comment]
非常感谢！我已经在activity上复现出来了。

**Comment by Shuyan98** [comment]
啊哦，我又上传了一次test_label，你再下载试试，应该是80列。复现出来就好，有什么问题随时沟通哈😄

**Comment by lpdone** [comment]
太棒啦~给学姐多点几个star

**Comment by lpdone** [comment]
您好，关于YFCC，我还有一个问题想请教。这么多的训练集文件是怎么训练的，是TrainDataset把所有文件的特征都读取，然后拼接成大矩阵，最后用DataLoader加载么？感觉这种操作是不可接受的。  还是说，一个训练文件训练完，再加载下一个训练文件，在1个epoch里面训练9次（9个训练文件，需要9个sim_matrix进行学习）。

预祝您新年快乐~

**Comment by Shuyan98** [comment]
是需要分成九个文件来训练，分别学习9个matrix，要不确实学不动哈。预祝学弟新年好！

**Comment by lpdone** [comment]
谢谢！

**Comment by tutusgithub** [comment]
> 非常感谢！我已经在activity上复现出来了。

你好，我想问一下，你在activity上复现出来的结果和论文中结果一致吗？

**Comment by rovgtjktm66** [comment]
> 

差别不大

**Comment by lpdone** [comment]
> > 非常感谢！我已经在activity上复现出来了。
> 
> 你好，我想问一下，你在activity上复现出来的结果和论文中结果一致吗？

差别不大

**Comment by lpdone** [comment]
> > 非常感谢！我已经在activity上复现出来了。
> 
> 你好，我想问一下，你在activity上复现出来的结果和论文中结果一致吗？

差别不大

**Comment by tutusgithub** [comment]
> > > 非常感谢！我已经在activity上复现出来了。
> > 
> > 
> > 你好，我想问一下，你在activity上复现出来的结果和论文中结果一致吗？
> 
> 差别不大

同学你好，我想请教一下，你在测试时用作者提供的query和database吗？有没有做改动，我复现的结果和论文中差了不少，不知道问题出在哪里了，我检查了感觉训练过程没什么问题，可否看看你的evaluation的代码，谢谢你
