### ISSUE TITLE
有关预训练的问题

### ISSUE THREAD

**Issue by huangmozhi9527** [Lily1994/BTH#4]
您好，我尝试在FCVID上完整地实现BTH，包括预训练。
我做了如下改动：epoch-->300，nbits-->128，loss-->mask_loss，evaluate-->save_nf。请问这样的改动是否完整？
还有我看mask_loss包含了两个video t1和t2。其中t2是根据t1和已有的sim_matrix.h5随机生成的，那么如果没有这个sim_matrix.h5文件，该如何改动预训练中的dataset和mask_loss呢？

**Comment by Shuyan98** [comment]
您好，你的设置是ok的。预训练只需要maskloss哈。对于预训练的话，比较方便的改法是把t2直接设置为t1就好了。
